import os

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import (
    HumanMessage,
    SystemMessage,
    ToolMessage,
)

from src.stores.domain.DomainFactory import DomainFactory


load_dotenv()

# Safety guardrail
MAX_ITERATIONS = 5

class AgenticAgent:

    def __init__(self, domain):

        self.domain = domain

        self.llm = ChatOpenAI(
            model="llama-3.3-70b-versatile",
            api_key=os.getenv("GROQ_API_KEY"),
            base_url="https://api.groq.com/openai/v1",
            temperature=0,
        )


        # Get tools from the selected domain
        # The agent does NOT know which domain it is using.
        # It simply receives the tools provided by that domain.

        self.tools = domain.tools

        # Create tool lookup
        # This allows the agent to execute any tool requested
        # by the LLM without hardcoding tool names.

        self.tools_by_name = {
            tool.name: tool
            for tool in self.tools
        }

        self.llm_with_tools = self.llm.bind_tools(
            self.tools
        )

    def answer(self, question: str):
        """
        Run the agentic loop for a single question.

        Returns:
            tuple[str, list[dict]]:
                - final answer text
                - full tool-call execution log, where each entry is:
                  {
                      "iteration": int,
                      "tool": str,
                      "arguments": dict,
                      "result": Any,
                  }
        """

        # Conversation history
        messages = [
            SystemMessage(
                content=self.domain.system_prompt
            ),
            HumanMessage(
                content=question
            ),
        ]

        all_tool_calls_log = []

        # ======================================================
        # Agentic loop
        #
        # LLM decides
        #       ↓
        # Python executes tool
        #       ↓
        # Tool result goes back to LLM
        #       ↓
        # LLM decides what to do next
        # ======================================================

        for iteration in range(1,MAX_ITERATIONS + 1):

            print(f"\n--- Iteration {iteration} ---")

            response = self.llm_with_tools.invoke(
                messages
            )

            # Keep the model response in conversation history
            messages.append(response)

            # No tool call
            # The LLM considers the answer complete.

            if not response.tool_calls:

                print(
                    "No further tool calls. "
                    "Returning final answer."
                )

                return response.content, all_tool_calls_log
            

            # Execute all tools requested by the LLM
            for tool_call in response.tool_calls:

                tool_name = tool_call["name"]
                tool_args = tool_call["args"]
                tool_call_id = tool_call["id"]

                print(f"Tool requested: {tool_name}")
                print(f"Arguments: {tool_args}")

                # Find requested tool
                tool = self.tools_by_name.get(tool_name)

                if tool is None:
                    result = (f"Unknown tool: {tool_name}")

                else:
                    try:
                        # Execute tool using arguments generated by LLM
                        result = tool.invoke(tool_args)

                    except Exception as error:

                        # Return tool errors to the LLM instead of
                        # crashing the entire agent.

                        result = (
                            f"Tool error: {error}"
                        )

                        print(result)

                # Save execution log
                all_tool_calls_log.append(
                    {
                        "iteration": iteration,
                        "tool": tool_name,
                        "arguments": tool_args,
                        "result": result,
                    }
                )

                # Send tool result back to the LLM
                # The tool_call_id connects this result to the
                # exact tool call made by the model.

                messages.append(
                    ToolMessage(
                        content=str(result),
                        tool_call_id=tool_call_id,
                    )
                )

        # Safety fallback
        # Prevent infinite tool-calling loops.

        messages.append(
            HumanMessage(
                content=(
                    "You have reached the maximum "
                    "number of tool-calling iterations. "
                    "Using ONLY the information already "
                    "gathered above, provide the best "
                    "final answer now. "
                    "Do not call any more tools."
                )
            )
        )

        final_response = self.llm.invoke(
            messages
        )

        return final_response.content, all_tool_calls_log


def main():

    #select domain
    domain = DomainFactory.create("hospitality")

    agent = AgenticAgent(domain)

    #question = ("What time is checkout")

    #out-of-scope request / hallucination guardrail
    question = ("What's the minibar pricing for the Executive Suite")

    #generate answer
    answer, log = agent.answer( question)

    print("\n" + "=" * 80)

    print("QUESTION:")
    print(question)

    print("\n" + "=" * 80)

    print("ANSWER:")
    print(answer)


if __name__ == "__main__":
    main()